In [1]:
%pip install psycopg2

Collecting psycopg2
  Downloading psycopg2-2.9.10-cp311-cp311-win_amd64.whl.metadata (5.0 kB)
Downloading psycopg2-2.9.10-cp311-cp311-win_amd64.whl (1.2 MB)
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   ------------------ --------------------- 0.5/1.2 MB 3.3 MB/s eta 0:00:01
   ---------------------------------------- 1.2/1.2 MB 4.4 MB/s eta 0:00:00
Installing collected packages: psycopg2
Successfully installed psycopg2-2.9.10
Note: you may need to restart the kernel to use updated packages.

In [1]:
import psycopg2
from psycopg2 import Error

## **ВАРИАНТ 3**
## Задание 1. Создайте базу данных "hospital_db" и подключитесь к ней.

In [ ]:
#Задание 1. Создайте базу данных "hospital_db" и подключитесь к ней.
import psycopg2

def get_connection(database_name):
    
    connection = psycopg2.connect(user="postgres",
                                  password="26102006",
                                  host="localhost",
                                  port="5432",
                                  database=database_name)
    return connection

def close_connection(connection):
   
    if connection:
        connection.close()
        print("Соединение с PostgreSQL закрыто")

try:
   
    connection = psycopg2.connect(user="postgres",
                                  password="26102006",
                                  host="localhost",
                                  port="5432",
                                  database="pr_7")
    connection.autocommit = True  
    cursor = connection.cursor()

  
    cursor.execute("CREATE DATABASE hospital_db;")
    print("База данных 'hospital_db' успешно создана")

    
    close_connection(connection)

    
    connection = get_connection("hospital_db")
    cursor = connection.cursor()

    # Создание таблицы Hospital
    create_table_query = '''
    CREATE TABLE Hospital (
        Hospital_Id serial NOT NULL PRIMARY KEY,
        Hospital_Name VARCHAR (100) NOT NULL,
        Bed_Count serial
    );
    '''
    cursor.execute(create_table_query)
    connection.commit()
    print("Таблица 'Hospital' успешно создана")

    # Вставка данных в таблицу
    insert_query = '''
    INSERT INTO Hospital (Hospital_Id, Hospital_Name, Bed_Count)
    VALUES
    (1, 'Mayo Clinic', 200),
    (2, 'Cleveland Clinic', 400),
    (3, 'Johns Hopkins', 1000),
    (4, 'UCLA Medical Center', 1500);
    '''
    cursor.execute(insert_query)
    connection.commit()
    print("Данные успешно вставлены в таблицу 'Hospital'")

    # Создание таблицы Doctor
    create_table_query = '''
    CREATE TABLE IF NOT EXISTS Doctor (
        Doctor_Id VARCHAR(10) PRIMARY KEY,
        Doctor_Name VARCHAR(100) NOT NULL,
        Hospital_Id INT NOT NULL,
        Joining_Date DATE,
        Speciality VARCHAR(100),
        Salary INT,
        Experience INT,
        FOREIGN KEY (Hospital_Id) REFERENCES Hospital(Hospital_Id)
    );
    '''
    cursor.execute(create_table_query)
    connection.commit()
    print("Таблица 'Doctor' успешно создана")

    # Вставка данных в таблицу Doctor
    insert_query = '''
    INSERT INTO Doctor (Doctor_Id, Doctor_Name, Hospital_Id, Joining_Date, Speciality, Salary, Experience)
    VALUES
        ('101', 'David', 1, '2005-02-10', 'Pediatric', 40000, NULL),
        ('102', 'Michael', 1, '2018-07-23', 'Oncologist', 20000, NULL),
        ('103', 'Susan', 2, '2016-05-19', 'Garnacologist', 25000, NULL),
        ('104', 'Robert', 2, '2017-12-28', 'Pediatric', 28000, NULL),
        ('105', 'Linda', 3, '2004-06-04', 'Garnacologist', 42000, NULL),
        ('106', 'William', 3, '2012-09-11', 'Dermatologist', 30000, NULL),
        ('107', 'Richard', 4, '2014-08-21', 'Garnacologist', 32000, NULL),
        ('108', 'Karen', 4, '2011-10-17', 'Radiologist', 30000, NULL),
        ('109', 'James', 1, '2022-01-15', 'Cardiologist', 45000, 5),
        ('110', 'Emily', 1, '2023-04-10', 'Orthopedic Surgeon', 50000, 3),
        ('111', 'Olivia', 2, '2021-09-05', 'Neurologist', 42000, 4),
        ('112', 'John', 2, '2024-02-18', 'Surgeon', 60000, 2),
        ('113', 'Sophia', 3, '2022-07-30', 'Urologist', 38000, 6),
        ('114', 'Daniel', 3, '2025-03-22', 'Pulmonologist', 47000, 1),
        ('115', 'Isabella', 4, '2023-11-01', 'Pediatrician', 41000, 3),
        ('116', 'Liam', 4, '2022-05-25', 'Dermatologist', 35000, 4),
        ('117', 'Mia', 1, '2024-06-17', 'Gastroenterologist', 53000, 2),
        ('118', 'Lucas', 2, '2023-01-12', 'Anesthesiologist', 46000, 3);
    '''
    cursor.execute(insert_query)
    connection.commit()
    print("Данные успешно вставлены в таблицу 'Doctor'")

except (Exception, psycopg2.Error) as error:
    print("Ошибка при подключении или работе с PostgreSQL:", error)

finally:
    
    if connection:
        close_connection(connection)

База данных 'hospital_db' успешно создана
Соединение с PostgreSQL закрыто
Таблица 'Hospital' успешно создана
Данные успешно вставлены в таблицу 'Hospital'
Таблица 'Doctor' успешно создана
Данные успешно вставлены в таблицу 'Doctor'
Соединение с PostgreSQL закрыто

## Задание 2. Заполните таблицу "Doctor" данными о 5 новых врачах.

In [27]:
#Задание 2. Заполните таблицу "Doctor" данными о 5 новых врачах.

def add_new_doctors():
    try:
        
        connection = psycopg2.connect(user="postgres",
                                      password="26102006",
                                      host="localhost",
                                      port="5432",
                                      database="hospital_db"
                                    )
        cursor = connection.cursor()

        
        insert_query = '''
        INSERT INTO Doctor (Doctor_Id, Doctor_Name, Hospital_Id, Joining_Date, Speciality, Salary, Experience)
        VALUES
            ('119', 'Anderson', 1, '2023-03-15', 'Neurosurgeon', 58000, 7),
            ('120', 'Wilson', 2, '2024-01-10', 'Cardiothoracic Surgeon', 62000, 5),
            ('121', 'Taylor', 3, '2022-11-20', 'Endocrinologist', 48000, 4),
            ('122', 'Martinez', 4, '2023-09-05', 'Ophthalmologist', 52000, 6),
            ('123', 'Robinson', 1, '2024-04-18', 'Psychiatrist', 45000, 3);
        '''
        cursor.execute(insert_query)
        connection.commit()
        print("5 новых врачей успешно добавлены в таблицу 'Doctor'")

    except psycopg2.Error as error:
        print("Ошибка при работе с PostgreSQL:", error)
        if connection:
            connection.rollback()
    finally:
        
        if connection:
            cursor.close()
            connection.close()
            print("Соединение с PostgreSQL закрыто")

add_new_doctors()

Ошибка при работе с PostgreSQL: ОШИБКА:  повторяющееся значение ключа нарушает ограничение уникальности "doctor_pkey"
DETAIL:  Ключ "(doctor_id)=(119)" уже существует.

Соединение с PostgreSQL закрыто

## Задание 3. Получите все записи из таблицы "Doctor", где зарплата > 30000.

In [7]:
# Задание 3. Получите все записи из таблицы "Doctor", где зарплата > 30000.

import psycopg2

def get_connection(database_name):
    connection = psycopg2.connect(user="postgres",
                                  password="26102006",
                                  host="localhost",
                                  port="5432",
                                  database=database_name)
    return connection

def close_connection(connection):
    if connection:
        connection.close()
        print("Соединение с PostgreSQL закрыто")

def get_doctors_with_high_salary():
    try:
        database_name = 'hospital_db'
        connection = get_connection(database_name)
        cursor = connection.cursor()

        # Пишем SQL-запрос для получения врачей, у которых зарплата больше 30000
        select_query = """
        SELECT * FROM Doctor 
        WHERE Salary > 30000
        """
        cursor.execute(select_query)
        records = cursor.fetchall()

        # Проверяем и выводим результаты
        print("\nСписок врачей с зарплатой больше 30000:\n")
        if records:
            for row in records:
                print("ID врача:", row[0])
                print("Имя врача:", row[1])
                print("ID больницы:", row[2])
                print("Дата начала работы:", row[3])
                print("Специальность:", row[4])
                print("Зарплата:", row[5])
                print("Опыт:", row[6], "\n")
        else:
            print("Врачи с зарплатой больше 30000 не найдены.")

        close_connection(connection)
    except (Exception, psycopg2.Error) as error:
        print("Ошибка при получении данных:", error)

print("Упражнение. Получение списка врачей с зарплатой больше 30000\n")
get_doctors_with_high_salary()

Упражнение. Получение списка врачей с зарплатой больше 30000


Список врачей с зарплатой больше 30000:

ID врача: 101
Имя врача: David
ID больницы: 1
Дата начала работы: 2005-02-10
Специальность: Pediatric
Зарплата: 40000
Опыт: None

ID врача: 105
Имя врача: Linda
ID больницы: 3
Дата начала работы: 2004-06-04
Специальность: Garnacologist
Зарплата: 42000
Опыт: None

ID врача: 107
Имя врача: Richard
ID больницы: 4
Дата начала работы: 2014-08-21
Специальность: Garnacologist
Зарплата: 32000
Опыт: None

ID врача: 109
Имя врача: James
ID больницы: 1
Дата начала работы: 2022-01-15
Специальность: Cardiologist
Зарплата: 45000
Опыт: 5

ID врача: 110
Имя врача: Emily
ID больницы: 1
Дата начала работы: 2023-04-10
Специальность: Orthopedic Surgeon
Зарплата: 50000
Опыт: 3

ID врача: 111
Имя врача: Olivia
ID больницы: 2
Дата начала работы: 2021-09-05
Специальность: Neurologist
Зарплата: 42000
Опыт: 4

ID врача: 112
Имя врача: John
ID больницы: 2
Дата начала работы: 2024-02-18
Специальность: Surgeon
Зарплата: 60000
Опыт: 2

ID врача: 113
Имя врача: Sophia
ID больницы: 3
Дата начала работы: 2022-07-30
Специальность: Urologist
Зарплата: 38000
Опыт: 6

ID врача: 114
Имя врача: Daniel
ID больницы: 3
Дата начала работы: 2025-03-22
Специальность: Pulmonologist
Зарплата: 47000
Опыт: 1

ID врача: 115
Имя врача: Isabella
ID больницы: 4
Дата начала работы: 2023-11-01
Специальность: Pediatrician
Зарплата: 41000
Опыт: 3

ID врача: 116
Имя врача: Liam
ID больницы: 4
Дата начала работы: 2022-05-25
Специальность: Dermatologist
Зарплата: 35000
Опыт: 4

ID врача: 117
Имя врача: Mia
ID больницы: 1
Дата начала работы: 2024-06-17
Специальность: Gastroenterologist
Зарплата: 53000
Опыт: 2

ID врача: 118
Имя врача: Lucas
ID больницы: 2
Дата начала работы: 2023-01-12
Специальность: Anesthesiologist
Зарплата: 46000
Опыт: 3

ID врача: 119
Имя врача: Anderson
ID больницы: 1
Дата начала работы: 2023-03-15
Специальность: Neurosurgeon
Зарплата: 58000
Опыт: 7

ID врача: 120
Имя врача: Wilson
ID больницы: 2
Дата начала работы: 2024-01-10
Специальность: Cardiothoracic Surgeon
Зарплата: 62000
Опыт: 5

ID врача: 121
Имя врача: Taylor
ID больницы: 3
Дата начала работы: 2022-11-20
Специальность: Endocrinologist
Зарплата: 48000
Опыт: 4

ID врача: 122
Имя врача: Martinez
ID больницы: 4
Дата начала работы: 2023-09-05
Специальность: Ophthalmologist
Зарплата: 52000
Опыт: 6

ID врача: 123
Имя врача: Robinson
ID больницы: 1
Дата начала работы: 2024-04-18
Специальность: Psychiatrist
Зарплата: 45000
Опыт: 3

Соединение с PostgreSQL закрыто

## Задание 4. Получите список всех врачей из больницы с ID=1.

In [10]:
#Задание 4. Получите список всех врачей из больницы с ID=1.
import psycopg2

def get_connection(database_name):
    connection = psycopg2.connect(user="postgres",
                                  password="26102006",
                                  host="localhost",
                                  port="5432",
                                  database=database_name)
    return connection

def close_connection(connection):
    if connection:
        connection.close()
        print("Соединение с PostgreSQL закрыто")

def get_hospital_1_doctors():
    try:
       
        connection = psycopg2.connect(user="postgres",
                                      password="26102006",
                                      host="localhost",
                                      port="5432",
                                      database="hospital_db"
                                    )
        cursor = connection.cursor()

        # Выбираем врачей из больницы, у которой ID = 1
        select_query = '''
        SELECT * FROM Doctor
        WHERE Hospital_Id = 1;
        '''
        
        cursor.execute(select_query)
        doctors = cursor.fetchall()

        
        print("\nВрачи из больницы с ID 1")
        print("-" * 50)
        for doctor in doctors:
           print(f"ID: {doctor[0]}")
           print(f"Имя: {doctor[1]}")
           print(f"Больница ID: {doctor[2]}")
           print(f"Дата приема: {doctor[3]}")
           print(f"Специальность: {doctor[4]}")
           print(f"Зарплата: ${doctor[5]}")
           print(f"Опыт: {doctor[6] or 'Не указан'} лет")
           print("-" * 50)
        return doctors

    except psycopg2.Error as error:
        print("Ошибка при работе с PostgreSQL:", error)
    finally:
        
        if connection:
            cursor.close()
            connection.close()
            print("\nСоединение с PostgreSQL закрыто")

get_hospital_1_doctors()

Врачи из больницы с ID 1
--------------------------------------------------
ID: 101
Имя: David
Больница ID: 1
Дата приема: 2005-02-10
Специальность: Pediatric
Зарплата: $40000
Опыт: Не указан лет
--------------------------------------------------
ID: 102
Имя: Michael
Больница ID: 1
Дата приема: 2018-07-23
Специальность: Oncologist
Зарплата: $20000
Опыт: Не указан лет
--------------------------------------------------
ID: 109
Имя: James
Больница ID: 1
Дата приема: 2022-01-15
Специальность: Cardiologist
Зарплата: $45000
Опыт: 5 лет
--------------------------------------------------
ID: 110
Имя: Emily
Больница ID: 1
Дата приема: 2023-04-10
Специальность: Orthopedic Surgeon
Зарплата: $50000
Опыт: 3 лет
--------------------------------------------------
ID: 117
Имя: Mia
Больница ID: 1
Дата приема: 2024-06-17
Специальность: Gastroenterologist
Зарплата: $53000
Опыт: 2 лет
--------------------------------------------------
ID: 119
Имя: Anderson
Больница ID: 1
Дата приема: 2023-03-15
Специальность: Neurosurgeon
Зарплата: $58000
Опыт: 7 лет
--------------------------------------------------
ID: 123
Имя: Robinson
Больница ID: 1
Дата приема: 2024-04-18
Специальность: Psychiatrist
Зарплата: $45000
Опыт: 3 лет
--------------------------------------------------

Соединение с PostgreSQL закрыто

[('101', 'David', 1, datetime.date(2005, 2, 10), 'Pediatric', 40000, None),
 ('102', 'Michael', 1, datetime.date(2018, 7, 23), 'Oncologist', 20000, None),
 ('109', 'James', 1, datetime.date(2022, 1, 15), 'Cardiologist', 45000, 5),
 ('110',
  'Emily',
  1,
  datetime.date(2023, 4, 10),
  'Orthopedic Surgeon',
  50000,
  3),
 ('117', 'Mia', 1, datetime.date(2024, 6, 17), 'Gastroenterologist', 53000, 2),
 ('119', 'Anderson', 1, datetime.date(2023, 3, 15), 'Neurosurgeon', 58000, 7),
 ('123', 'Robinson', 1, datetime.date(2024, 4, 18), 'Psychiatrist', 45000, 3)]

## Задание 5. Используйте Pandas для агрегации зарплаты врачей по специальностям.

In [ ]:
# Задание 5. Используйте Pandas для агрегации зарплаты врачей по специальностям.
import psycopg2
import pandas as pd

def get_connection(database_name):
    connection = psycopg2.connect(user="postgres",
                                  password="26102006",
                                  host="localhost",
                                  port="5432",
                                  database=database_name)
    return connection

def close_connection(connection):
    if connection:
        connection.close()
        print("Соединение с PostgreSQL закрыто")

def aggregate_salary_by_speciality():
    try:
        database_name = 'hospital_db'
        connection = get_connection(database_name)
        cursor = connection.cursor()

        # Пишем SQL запрос для получения данных о врачах, содержащие специальности и зарплату
        select_query = """
        SELECT Speciality, Salary 
        FROM Doctor
        """
        cursor.execute(select_query)

        # Загружаем наши результаты в DataFrame
        records = cursor.fetchall()
        df = pd.DataFrame(records, columns=['Speciality', 'Salary'])

        # Теперь группируем данные по специальности и суммируем зарплату в каждой специальности
        salary_aggregation = df.groupby('Speciality').agg({'Salary': 'sum'}).reset_index()

        # Выводим результат
        print("\nАгрегация зарплаты врачей по специальностям:\n")
        print(salary_aggregation)

      
        close_connection(connection)
    except (Exception, psycopg2.Error) as error:
        print("Ошибка при получении данных:", error)


print("Упражнение. Агрегация зарплаты врачей по специальностям\n")
aggregate_salary_by_speciality()

Упражнение. Агрегация зарплаты врачей по специальностям


Агрегация зарплаты врачей по специальностям:

                Speciality  Salary
0         Anesthesiologist   46000
1             Cardiologist   45000
2   Cardiothoracic Surgeon   62000
3            Dermatologist   65000
4          Endocrinologist   48000
5            Garnacologist   99000
6       Gastroenterologist   53000
7              Neurologist   42000
8             Neurosurgeon   58000
9               Oncologist   20000
10         Ophthalmologist   52000
11      Orthopedic Surgeon   50000
12               Pediatric   68000
13            Pediatrician   41000
14            Psychiatrist   45000
15           Pulmonologist   47000
16             Radiologist   30000
17                 Surgeon   60000
18               Urologist   38000
Соединение с PostgreSQL закрыто